FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["ClashApi/ClashApi.csproj", "ClashApi/"]
RUN dotnet restore "ClashApi/ClashApi.csproj"
COPY . .
WORKDIR "/src/ClashApi"
RUN dotnet build "ClashApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ClashApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ClashApi.dll"]
